# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      julia: 0.6
    - os: linux
      julia: nightly
    - os: linux
      julia: 0.6
      env: DIRECTOR_BUILD_FROM_SOURCE=1
    - os: linux
      julia: nightly
      env: DIRECTOR_BUILD_FROM_SOURCE=1
    - os: osx
      julia: 0.6

notifications:
  email: false
branches:
  only: master
after_success:
  - julia -e 'cd(Pkg.dir("DrakeVisualizer")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
